add -fvia-c to ghc-options
Peculiarly, if one tries to go through -fasm, this causes link errors ie for Hetris: '/home/gwern/bin/lib/hscurses-1.2/ghc-6.8.2/libHShscurses-1.2.a(Curses.o): In function `r9qr_info':
(.text+0x12054): undefined reference to `hs_curses_color_pair''

I think this must be a general property of anything FFI'ng ncurses, since Mage uses its own fairly different curses binding and *it* needs to go -fvia-c as well!

darcs-hash:20080306022459-f7719-99c50545410024db32387ad51b6edbff3a4f1c76.gz